
import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    background: {
      flex: 1,
    },
    container: {
      flex: 1,
      paddingTop: 40,
      paddingHorizontal: 20,
      justifyContent: 'center',
    },
    stepContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      paddingBottom: 60,
      paddingTop: 40,
      overflow: 'visible',
    },
    animation: {
      width: 300,
      height: 300,
    },
    animationSmall: {
      width: 250,
      height: 250,
    },
    questionAnimation: {
      width: 180,
      height: 180,
      marginBottom: 10,
    },
    textContainer: {
      alignItems: 'center',
      marginBottom: 40,
    },
    welcomeText: {
      fontSize: 28,
      fontWeight: '300',
      color: '#333',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    appNameText: {
      fontSize: 42,
      fontWeight: 'bold',
      color: '#6200ee',
      marginTop: 5,
      textShadowColor: 'rgba(0,0,0,0.1)',
      textShadowOffset: {width: 1, height: 1},
      textShadowRadius: 2,

    },
    welcomeDescription: {
      fontSize: 16,
      color: '#666',
      marginTop: 10,
      textAlign: 'center',
      marginBottom:20,
    },
    questionnaireOptions: {
      width: '100%',
      alignItems: 'center',
      marginTop: 20,
    },
    questionnairePrompt: {
      fontSize: 18,
      color: '#333',
      textAlign: 'center',
      marginBottom: 24,
      paddingHorizontal: 20,
    },
    optionsContainer: {
      width: '100%',
    },
    optionButton: {
      backgroundColor: '#6200ee',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 30,
      alignItems: 'center',
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    optionButtonSecondary: {
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: '#6200ee',
    },
    optionButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    optionButtonTextSecondary: {
      color: '#6200ee',
      fontSize: 16,
      fontWeight: '600',
    },
    stepTitle: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#6200ee',
      textAlign: 'center',
      marginBottom: 16,
    },
    stepDescription: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginBottom: 40,
      paddingHorizontal: 10,
      lineHeight: 24,
    },
    questionTitle: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#333',
      textAlign: 'center',
      marginBottom: 8,
      paddingHorizontal: 10,
      textShadowColor: 'rgba(255,255,255,0.7)',
      textShadowOffset: {width: 0, height: 1},
      textShadowRadius: 2,
    },
    questionDescription: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginBottom: 30,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 10,
    },
    sliderContainer: {
      width: '100%',
      marginBottom: 20,
    },
    slider: {
      width: '100%',
      height: 40,
    },
    sliderLabelsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: 5,
    },
    sliderLabel: {
      color: '#666',
      fontSize: 14,
    },
    selectedValue: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#6200ee',
      marginTop: 16,
      textAlign: 'center',
      backgroundColor: 'rgba(255,255,255,0.7)',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
    },
    selectionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      width: '100%',
    },
    selectionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 15,
      width: '48%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
    },
    selectedButton: {
      backgroundColor: '#6200ee',
      borderColor: '#6200ee',
    },
    buttonIcon: {
      marginRight: 8,
    },
    selectionButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#333',
    },
    selectedButtonText: {
      color: 'white',
    },
    circularSelectionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      width: '100%',
      marginBottom: 20,
      flexWrap: 'wrap',
    },
    circularButton: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
      margin: 6,
    },
    selectedCircularButton: {
      backgroundColor: '#6200ee',
      borderColor: '#6200ee',
    },
    circularButtonText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
    },
    selectedCircularButtonText: {
      color: 'white',
    },
    scrollableSelections: {
      maxHeight: 300,
      width: '100%',
    },
    scrollContent: {
      paddingBottom: 20,
    },
    nextButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6200ee',
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 30,
      marginTop: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
    },
    nextButtonText: {
      color: 'white',
      fontWeight: '600',
      fontSize: 16,
      marginRight: 8,
    },
    disabledButton: {
      backgroundColor: '#cccccc',
      shadowOpacity: 0.1,
    },
    backButton: {
      position: 'absolute',
      top: 60,
      left: 20,
      zIndex: 10,
      padding: 8,
    },
    progressContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      position: 'absolute',
      top: 50,
      left: 0,
      right: 0,
      zIndex: 5,
    },
    progressDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#e0e0e0',
      marginHorizontal: 4,
    },
    progressDotActive: {
      backgroundColor: '#6200ee',
      borderRadius: 5,
    },
    socialButtonsContainer: {
      width: '100%',
      marginBottom: 16,
    },
    socialButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 30,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#e9ecef',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    facebookButton: {
      backgroundColor: '#1877f2',
      borderColor: '#1877f2',
    },
    googleButton: {
      backgroundColor: 'white',
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    socialIconLarge: {
      width: 28,
      height: 28,
      marginRight: 12,
    },
    socialButtonTextLarge: {
      fontSize: 16,
      fontWeight: '600',
    },
    finalTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#6200ee',
      marginBottom: 40,
      textAlign: 'center',
    },
    authOptions: {
      width: '100%',
    },
    largeActionButton: {
      backgroundColor: '#6200ee',
      width: '100%',
      paddingVertical: 16,
      borderRadius: 30,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
    },
    largeActionButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    loginPrompt: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 24,
    },
    loginText: {
      color: '#757575',
      fontSize: 16
    },
    optionButtonSecundary:{
      backgroundColor: 'transparent',
      borderColor: '#6200ee',
      color: '#6200ee',
    },
    questionsContainer: {
      width: '100%',
      paddingHorizontal: 20,
    },
    questionItem: {
      marginBottom: 15,
    },
    questionText: {
      fontSize: 16,
      fontWeight: '500',
      marginBottom: 10,
    },
    navigationButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 15,
    },
    navButton: {
      backgroundColor: '#3498db',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 5,
      minWidth: 100,
      alignItems: 'center',
    },
    navButtonText: {
      color: 'white',
      fontWeight: '500',
    },
    lottieAnimation: {
      width: 150,
      height: 150,
      alignSelf: 'center',
    },
    scrollableSections: {
      maxHeight: 300,
      width: '100%',
    },
    yesNoContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '60%',
      marginVertical: 20,
    },
    yesNoButton: {
      width: '45%',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: '#e0e0e0',
      backgroundColor: 'white',
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectedYesNoButton: {
      backgroundColor: '#6200ee',
      borderColor: '#6200ee',
    },
    yesNoButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
    },
    selectedYesNoButtonText: {
      color: 'white',
    },
    textInputContainer: {
      width: '100%',
      marginTop: 10,
    },
    textInputLabel: {
      fontSize: 14,
      color: '#666',
      marginBottom: 5,
    },
    textInput: {
      backgroundColor: 'white',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      borderRadius: 8,
      padding: 12,
      width: '100%',
      textAlignVertical: 'top',
    },
    loginLink: {
      color: '#6200ee',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 5,
    },
    confirmationCard: {
      backgroundColor: 'white',
      borderRadius: 16,
      padding: 20,
      width: '90%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
      maxHeight: '70%',
      overflow: 'scroll'
    },
    confirmationTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#6200ee',
      textAlign: 'center',
      marginBottom: 12,
    },
    conformationDesciption: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginBottom: 20,
      lineHeight: 22,
    },
    planHighlight: {
      marginTop: 10,
    },
    highlightItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    hightlightText: {
      fontSize: 16,
      color: '#333',
      marginLeft: 10,
      flex: 1,
      flexWrap: 'wrap',
    },
    animationContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    }
  });