version: '3.8'

services:
  backend:
    build:
      context: .. # Changed from ../.. to ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./../backend:/app

  frontend:
    build:
      context: .. # Changed from ../.. to ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./..:/app
      - /app/node_modules
